Repository pieces-app/documentation, pull requests merged in 2023-05, with the labels that each got.

#17 Georgia edits
  docs/extensions-plugins-support/troubleshooting-chrome.mdx
  docs/extensions-plugins-support/troubleshooting-jetbrains.mdx
Labels: copy

#19 Upgrading the styles across documentation
  README.md
  docs.json
  docs/additional-features-and-settings.mdx
  docs/assets/chrome_extension.png
  docs/assets/chrome_share_button.png
  docs/assets/settings_for_chrome.png
  docs/assets/theme_for_chrome.png
  docs/assets/what_am_installing.png
  docs/extensions-plugins-support/troubleshooting-chrome.mdx
  docs/faq.mdx
  docs/features/auto-enrichment.mdx
  docs/features/creation-and-generation.mdx
  docs/features/global-search.mdx
  docs/features/managing-saved-materials.mdx
  docs/features/one-click-snippet-sharing.mdx
  docs/features/workflow-activity.mdx
  docs/index.mdx
  docs/installation-getting-started/linux.mdx
  docs/installation-getting-started/macos.mdx
  docs/installation-getting-started/what-am-i-installing.mdx
  docs/installation-getting-started/windows.mdx
  docs/overview.mdx
  docs/product-highlights-and-benefits/import-gists-from-github.mdx
  docs/product-highlights-and-benefits/in-project-snippet-discovery.mdx
  docs/product-highlights-and-benefits/privacy-security-data.mdx
  docs/product-highlights-and-benefits/saving-screenshots.mdx
  docs/product-highlights-and-benefits/saving-useful-developer-materials.mdx
Labels: enhancement, style, section

#22 Community updates
  docs/our-community.mdx
Labels: new, enhancement, style, section

#23 Typo Updated
  docs/faq.mdx
Labels: copy

#25 Configuration for buttons on all of the plugins page based off chrome
  docs.json
  docs/extensions-plugins-support/troubleshooting-chrome.mdx
  docs/extensions-plugins-support/troubleshooting-edge.mdx
  docs/extensions-plugins-support/troubleshooting-jetbrains.mdx
  docs/extensions-plugins-support/troubleshooting-vscode.mdx
Labels: new, enhancement, section

#29 Teams Page for Applications
  docs.json
  docs/assets/teams/marketplace_screenshot.png
  docs/assets/teams/open_in_location_zoomed.png
  docs/extensions-plugins/teams.mdx
Labels: new, page

#30 Test Partnership Collection Page
  docs/assets/partner-collections/save_this_button.png
  docs/assets/partner-collections/save_this_snippet_example.png
  docs/partnership-collection/dart-tutorial.mdx
Labels: new, section, page

#32 Rich edits installtion paths
  docs/index.mdx
  docs/installation-getting-started/what-am-i-installing.mdx
  docs/overview.mdx
Labels: enhancement, style, copy

#33 Patch edits
  docs.json
  docs/assets/linux_logo.png
  docs/assets/mac_os.png
  docs/assets/windows_logo_old.png
  docs/index.mdx
Labels: enhancement, style, update

#39 Redirects, Install Overview Update + more
  README.md
  docs.json
  docs/%7B%7B%20links.internal.faq%20%7D%7D.mdx
  docs/%7B%7B%20links.socials.support%20%7D%7D.mdx
  docs/additional-features-and-settings.mdx
  docs/assets/installation/robots_linux.png
  docs/assets/installation/robots_macos.png
  docs/assets/installation/robots_windows.png
  docs/assets/pfd_logo.png
  docs/assets/teams_logo.png
  docs/context-awareness-engine/%7B%7B%20links.internal.share_via_github_gist%20%7D%7D.mdx
  docs/extensions-plugins-support/%7B%7B%20links.installation.pfd_desktop_install%20%7D%7D.mdx
  docs/extensions-plugins-support/%7B%7B%20links.socials.support%20%7D%7D.mdx
  docs/extensions-plugins-support/troubleshooting-chrome.mdx
  docs/extensions-plugins-support/troubleshooting-edge.mdx
  docs/extensions-plugins-support/troubleshooting-jetbrains.mdx
  docs/extensions-plugins-support/troubleshooting-vscode.mdx
  docs/extensions-plugins-support/{{%20links.installation.pfd_desktop_install%20}}.mdx
  docs/extensions-plugins-support/{{%20website.links.home%20}}.mdx
  docs/extensions-plugins/chrome.mdx
  docs/extensions-plugins/edge.mdx
  docs/extensions-plugins/jetbrains.mdx
  docs/extensions-plugins/teams.mdx
  docs/extensions-plugins/vscode.mdx
  docs/features/auto-enrichment.mdx
  docs/features/code-completion.mdx
  docs/features/global-search.mdx
  docs/features/one-click-snippet-sharing.mdx
  docs/global-search-suggestion-reuse/%5Bobject%20Object%5D.mdx
  docs/index.mdx
  docs/installation-getting-started/linux.mdx
  docs/installation-getting-started/macos.mdx
  docs/installation-getting-started/what-am-i-installing.mdx
  docs/installation-getting-started/windows.mdx
  docs/overview.mdx
  docs/personalized-link-sharing/%7B%7B%20links.website.jetbrains%20%7D%7D.mdx
  docs/product-highlights-and-benefits/%7B%7B%20website.internal.product_highlights.in_project_snippet_discovery%20%7D%7D.mdx
  docs/product-highlights-and-benefits/%7B%7B%20website.links.home%20%7D%7D.mdx
  docs/product-highlights-and-benefits/import-gists-from-github.mdx
  docs/product-highlights-and-benefits/in-project-snippet-discovery.mdx
  docs/product-highlights-and-benefits/saving-screenshots.mdx
  docs/product-highlights-and-benefits/saving-useful-developer-materials.mdx
  docs/use-cases/%7B%7B%20links.internal.global_search_suggestion_reuse.sort_Scope_relevant%20%7D%7D.mdx
  docs/use-cases/%7B%7B%20links.internal.product_highlights,in_project_snippet_discovery%20%7D%7D.mdx
Labels: enhancement, style, seo/meta

#40 Overview what am installing upgrade
  docs.json
  docs/assets/installation/tabs/macos/dark_light_mode.png
  docs/assets/installation/tabs/macos/discover_inproject.png
  docs/assets/installation/tabs/macos/extract_screenshots.png
  docs/assets/installation/tabs/macos/keyboard_shortcuts.png
  docs/assets/installation/tabs/macos/manage_context.png
  docs/assets/installation/tabs/macos/quickly_save.png
  docs/assets/installation/tabs/macos/responsive_layout.png
  docs/assets/installation/tabs/macos/single_click.png
  docs/assets/installation/tabs/macos/view_and_edit.png
  docs/assets/magnifying_glass.png
  docs/assets/shield.png
  docs/index.mdx
  docs/installation-getting-started/what-am-i-installing.mdx
Labels: enhancement, style, copy

#41 Pieces for Developers Download rework + addition on sidebar
  docs.json
Labels: new, enhancement, update
