Repository pieces-app/documentation, pull requests merged in 2023-07, with the labels that each got.

#81 Updated CTA's on overview - other changes also included
  docs.json
  docs/extensions-plugins/chrome.mdx
  docs/extensions-plugins/edge.mdx
  docs/extensions-plugins/jetbrains.mdx
  docs/extensions-plugins/jupyterlab.mdx
  docs/extensions-plugins/obsidian.mdx
  docs/extensions-plugins/teams.mdx
  docs/extensions-plugins/vscode.mdx
  docs/features/transforming-snippets.mdx
  docs/index.mdx
  docs/installation-getting-started/linux.mdx
  docs/installation-getting-started/what-am-i-installing.mdx
  docs/privacy-policy.mdx
Labels: style, copy

#74 New Features June 2023 - Patches and Issues Combined
  docs.json
  docs/assets/nodejs_collection_card.png
  docs/features/global-search.mdx
  docs/features/keyboard-shortcuts.mdx
  docs/features/managing-saved-materials.mdx
  docs/features/pieces-copilot.mdx
  docs/features/transforming-snippets.mdx
  docs/features/user-settings.mdx
  docs/features/workflow-activity.mdx
  docs/installation-getting-started/macos.mdx
  docs/installation-getting-started/windows.mdx
  docs/product-highlights-and-benefits/collections.mdx
  docs/product-highlights-and-benefits/privacy-security-data.mdx
Labels: new, page

#87 Copy Edits & Typo Fixes
  docs/features/pieces-copilot.mdx
  docs/features/user-settings.mdx
Labels: copy

#89 Patches & Updates for July
  docs.json
  docs/features/keyboard-shortcuts.mdx
  docs/index.mdx
  docs/product-highlights-and-benefits/collections.mdx
Labels: enhancement, copy, requests

#103 Jupyter installation format
  docs/extensions-plugins/jupyterlab.mdx
Labels: enhancement
