Repository pieces-app/documentation, pull requests merged in 2023-12, with the labels that each got.

#196 Dec 1 updates (combined stragglers from NOV checklist)
  docs.json
  docs/assets/soc-2-badge.png
  docs/features/search-modes.mdx
  docs/installation-getting-started/what-am-i-installing.mdx
  docs/product-highlights-and-benefits/privacy-security-data.mdx
Labels: copy

#189 Azure Data Studio: Sidebar, new page, updated copy, new icon for ADS
  docs.json
  docs/assets/ads_logo.png
  docs/extensions-plugins/azuredatastudio.mdx
Labels: new, page

#204 added to the intellij/jetbrains extension page, improve instructions
  docs/extensions-plugins/jetbrains.mdx
Labels: new, section, copy

#206 updates for jcef - typos: AA -> a and ending statement on android studio
  docs/extensions-plugins/jetbrains.mdx
Labels: copy

#193 docs: Add two new methods for connecting to a remote Pieces OS instance
  docs/product-highlights-and-benefits/connecting-to-a-remote-pieces-os-instance.mdx
Labels: new, section
