Repository pieces-app/documentation, pull requests merged in 2023-06, with the labels that each got.

#46 feat: Obsidian Docs Page
  docs.json
  docs/assets/obsidian/OBSIDIAN_RIGHTCLICK.gif
  docs/assets/obsidian/OBSIDIAN_SAVE.gif
  docs/assets/obsidian/OBSIDIAN_SEARCH.gif
  docs/assets/obsidian/OBSIDIAN_SHARE.gif
  docs/assets/obsidian/OBSIDIAN_VIEWPIECE.gif
  docs/assets/obsidian_logo.png
  docs/extensions-plugins/obsidian.mdx
Labels: enhancement

#53 chore: Fix Keyboard Shortcuts
  docs/extensions-plugins/obsidian.mdx
Labels: copy

#45 Copy upgrades and Docs Improvements
  README.md
  docs.json
  docs/features/auto-enrichment.mdx
  docs/features/creation-and-generation.mdx
  docs/features/global-search.mdx
  docs/features/managing-saved-materials.mdx
  docs/features/one-click-snippet-sharing.mdx
  docs/features/transforming-snippets.mdx
  docs/global-search-suggestion-reuse/adjusting-settings-for-search.mdx
  docs/global-search-suggestion-reuse/global-search.mdx
  docs/global-search-suggestion-reuse/sort-scope-relevant.mdx
  docs/global-search-suggestion-reuse/workflow-activity-stream.mdx
  docs/global-search-suggestion-reuse/workflow-activity.mdx
  docs/new-to-pieces/getting-started.mdx
  docs/new-to-pieces/how-our-search-works.mdx
  docs/personalized-link-sharing/saving-for-offline.mdx
  docs/personalized-link-sharing/share-via-github-gist.mdx
  docs/personalized-link-sharing/single-click-link-sharing.mdx
  docs/product-highlights-and-benefits/import-gists-from-github.mdx
  docs/product-highlights-and-benefits/in-project-snippet-discovery.mdx
  docs/product-highlights-and-benefits/saving-screenshots.mdx
  docs/product-highlights-and-benefits/saving-useful-developer-materials.mdx
Labels: copy

#55 Branch for Coles Review of Copy Upgrades
  docs/extensions-plugins/obsidian.mdx
  docs/faq.mdx
  docs/features/auto-enrichment.mdx
  docs/features/code-completion.mdx
  docs/features/creation-and-generation.mdx
  docs/features/global-search.mdx
  docs/features/managing-saved-materials.mdx
  docs/features/one-click-snippet-sharing.mdx
  docs/features/transforming-snippets.mdx
  docs/features/workflow-activity.mdx
  docs/product-highlights-and-benefits/import-gists-from-github.mdx
  docs/product-highlights-and-benefits/in-project-snippet-discovery.mdx
  docs/product-highlights-and-benefits/privacy-security-data.mdx
  docs/product-highlights-and-benefits/saving-screenshots.mdx
  docs/product-highlights-and-benefits/saving-useful-developer-materials.mdx
Labels: enhancement, copy

#58 fix: One click snippet sharing broken link
  docs.json
Labels: config

#75 Updated Plugin Section
  docs/extensions-plugins/chrome.mdx
  docs/extensions-plugins/edge.mdx
  docs/extensions-plugins/jetbrains.mdx
  docs/extensions-plugins/jupyterlab.mdx
  docs/extensions-plugins/teams.mdx
  docs/extensions-plugins/vscode.mdx
  docs/index.mdx
  docs/installation-getting-started/linux.mdx
  docs/installation-getting-started/macos.mdx
  docs/installation-getting-started/windows.mdx
Labels: style, page
