Repository pieces-app/documentation, pull requests merged in 2023-11, with the labels that each got.

#170 Dart tutorial updates
  docs/partnership-collection/dart-tutorial.mdx
  documentation.iml
Labels: new, section, copy

#172 17/32 Changes made - Nov major updates
  README.md
  docs.json
  docs/extensions-plugins/chrome.mdx
  docs/extensions-plugins/edge.mdx
  docs/extensions-plugins/jetbrains.mdx
  docs/extensions-plugins/jupyterlab.mdx
  docs/extensions-plugins/obsidian.mdx
  docs/extensions-plugins/teams.mdx
  docs/extensions-plugins/vscode.mdx
  docs/features/pieces-copilot.mdx
  docs/installation-getting-started/linux.mdx
  docs/installation-getting-started/macos.mdx
  docs/installation-getting-started/pieces-os.mdx
  docs/installation-getting-started/what-am-i-installing.mdx
  docs/installation-getting-started/windows.mdx
Labels: enhancement, copy

#175 All changes from #cole for november community page upgrade
  docs/our-community.mdx
Labels: enhancement, copy

#180 docs: Update index.mdx description text
  docs/index.mdx
Labels: copy

#183 docs: Update connecting to a remote Pieces OS instance description
  docs.json
  docs/product-highlights-and-benefits/connecting-to-a-remote-pieces-os-instance.mdx
Labels: style, copy

#185 New page addition for Mozilla Firefox Extension
  docs.json
  docs/extensions-plugins/chrome.mdx
  docs/extensions-plugins/firefox.mdx
Labels: new, copy, page

#188 chrome copilot .gif added
  docs/extensions-plugins/chrome.mdx
Labels: new, image refresh
