Repository pieces-app/documentation, pull requests merged in 2023-10, with the labels that each got.

#162 Backup and Restore Page
  .github/workflows/git-actions.yml
  .idea/workspace.xml
  docs.json
  docs/assets/backup_database/navigate_to_home.png
  docs/assets/backup_database/replace_message.png
  docs/assets/backup_database/selecting_library_folder.png
  docs/assets/backup_database/selecting_pieces_folders.png
  docs/assets/backup_database/title_archive.png
  docs/assets/obsidian_logo.png
  docs/extensions-plugins/chrome.mdx
  docs/extensions-plugins/edge.mdx
  docs/extensions-plugins/jetbrains.mdx
  docs/extensions-plugins/jupyterlab.mdx
  docs/extensions-plugins/obsidian.mdx
  docs/extensions-plugins/teams.mdx
  docs/extensions-plugins/vscode.mdx
  docs/features/back-up-and-restore.mdx
  docs/index.mdx
  docs/installation-getting-started/windows.mdx
Labels: page

#165 Quick patches for @cole on index + redirects
  .idea/workspace.xml
  docs/index.mdx
  docs/overview.mdx
Labels: bug

#168 Updates to Chrome documentation
  docs/extensions-plugins/chrome.mdx
Labels: copy
