Repository pieces-app/documentation, pull requests merged in 2024-02, with the labels that each got.

#251 Update pieces-copilot.mdx
  docs/features/pieces-copilot.mdx
Labels: copy, image refresh, community collaboration

#261 Update to feedback support link
  docs.json
Labels: config, links

#254 Preview Link, No follow research, Expanding docs.page functionality
  .github/workflows/preview-link.yml
  docs/dev/internal/testing/testing.mdx
  docs/installation-getting-started/windows.mdx
Labels: enhancement, organizational, internal
