Repository pieces-app/documentation, pull requests merged in 2024-01, with the labels that each got.

#208 feat: vscode copilot entry and copilot plugin page
  docs.json
  docs/extensions-plugins/jetbrains.mdx
  docs/extensions-plugins/jupyterlab.mdx
  docs/extensions-plugins/obsidian.mdx
  docs/extensions-plugins/vscode.mdx
  docs/features/copilot-plugin.mdx
  docs/features/pieces-copilot.mdx
Labels: enhancement

#235 Update minimum supported macOS Monterey version
  docs/installation-getting-started/macos.mdx
Labels: enhancement

#234 feat(docs): Update LLM names and descriptions
  docs/assets/_azuredatastudio_out/readme.ads.md
  docs/extensions-plugins/obsidian.mdx
  docs/features/copilot-plugin.mdx
  docs/features/pieces-copilot.mdx
Labels: copy

#232 fix(docs): Update installation button text
  docs/installation-getting-started/linux.mdx
  docs/installation-getting-started/macos.mdx
  docs/installation-getting-started/pieces-os.mdx
  docs/installation-getting-started/windows.mdx
Labels: copy

#248 Adjusting borderRadius and testing build changes
  docs.json
  docs/.DS_Store
  docs/extensions-plugins/azuredatastudio.mdx
  docs/extensions-plugins/chrome.mdx
  docs/extensions-plugins/edge.mdx
  docs/extensions-plugins/firefox.mdx
  docs/extensions-plugins/jetbrains.mdx
  docs/extensions-plugins/jupyterlab.mdx
  docs/extensions-plugins/obsidian.mdx
  docs/extensions-plugins/teams.mdx
  docs/extensions-plugins/vscode.mdx
  docs/features/creation-and-generation.mdx
  docs/features/search-modes.mdx
  docs/index.mdx
  docs/installation-getting-started/macos.mdx
  docs/installation-getting-started/pieces-os.mdx
  docs/installation-getting-started/what-am-i-installing.mdx
  docs/installation-getting-started/windows.mdx
  docs/product-highlights-and-benefits/sync-across-multiple-devices-using-github.mdx
Labels: enhancement, style
